# Limiting and Stationary Distribution of Markov Chain

In [19]:
# Import packages
import numpy as np
from numpy import linalg 

In [20]:
# Transition matrix
P = np.array([[0.8,0.2,0],[0.1,0.8,0.1],[0,0.2,0.8]])
print(P)

# Calculate the power of P
print("P^2 is", np.linalg.matrix_power(P,2))

[[0.8 0.2 0. ]
 [0.1 0.8 0.1]
 [0.  0.2 0.8]]
P^2 is [[0.66 0.32 0.02]
 [0.16 0.68 0.16]
 [0.02 0.32 0.66]]


In [21]:
# P to the power 20
print(np.linalg.matrix_power(P,20))

[[0.25577375 0.49998172 0.24424453]
 [0.24999086 0.50001828 0.24999086]
 [0.24424453 0.49998172 0.25577375]]


Approximate $\lim_{n\to\infty}P^n$ by taking $n$ to be a large enough number.

In [28]:
# P to the power 200, which can approximate lim_{n\to\infty}P^n
P_limit = np.linalg.matrix_power(P,200)
print(P_limit)

[[0.25 0.5  0.25]
 [0.25 0.5  0.25]
 [0.25 0.5  0.25]]


Now let's calculate the limiting distribution of this Markov chain for some given initial distributions. We will see an interesting phenomenon that no matter what initial distribution we take, the limiting distribution of the Markov chain is always the same.

In [31]:
# alpha1 as initial distribution
alpha_1 = np.array([1.0,0.0,0.0])
lim_dist_1 = alpha_1 @ P_limit # operator @ for matrix product
print('When such initial distribution is taken, the distribution of $X_1$ is:')
print(alpha_1 @ P)
print('The limiting distribution is:')
print(lim_dist_1)

When such initial distribution is taken, the distribution of $X_1$ is:
[0.8 0.2 0. ]
The limiting distribution is:
[0.25 0.5  0.25]


In [32]:
# alpha2 as initial distribution and its limiting distribution lim_dist_1
alpha_2 = np.array([0.3,0.2,0.5])
lim_dist_2 = alpha_2 @ P_limit # operator @ for matrix product
print('When such initial distribution is taken, the distribution of $X_1$ is:')
print(alpha_2 @ P)
print('The limiting distribution is:')
print(lim_dist_2)

When such initial distribution is taken, the distribution of $X_1$ is:
[0.26 0.32 0.42]
The limiting distribution is:
[0.25 0.5  0.25]


In [33]:
# alpha3 as initial distribution and its limiting distribution lim_dist_1
alpha_3 = np.array([0.67,0.24,0.09])
lim_dist_3 = alpha_3 @ P_limit # operator @ for matrix product
print('When such initial distribution is taken, the distribution of $X_1$ is:')
print(alpha_3 @ P)
print('The limiting distribution is:')
print(lim_dist_3)

When such initial distribution is taken, the distribution of $X_1$ is:
[0.56  0.344 0.096]
The limiting distribution is:
[0.25 0.5  0.25]


It seems magical that no matter what initial distribution we take for this Markov chain, it always converges to the same limiting distribution $\pi^T = [0.25,0.5,0.25]$. We show in the following context that such $\pi^T$ is actually the stationary distribution of the Markov chain.

To calculate stationary distribution numerically, let's adopt the eigenvector interpretation of stationary distribution that it's the eigenvector of $P^T$ corresponding to eigenvalue $1$.

In [12]:
# Get eigen-decomposition of P^T
[eigenval,eigenvect] = linalg.eig(np.transpose(P))
eigenvect

array([[ 4.08248290e-01,  7.07106781e-01,  4.08248290e-01],
       [-8.16496581e-01, -2.01786028e-15,  8.16496581e-01],
       [ 4.08248290e-01, -7.07106781e-01,  4.08248290e-01]])

In [13]:
eigenval

array([0.6, 0.8, 1. ])

Eigenvectors are the **columns** of eigenvect. The returned columns are not normalized, so once we figure which column we want (which is the one where eigenval = 1), we must normalize it.

In [35]:
# Take the eigenvector corresponding to eigenvalue 1 and normalize it such that all its components sum up to 1
stat_dist = eigenvect[:,2] / np.sum(eigenvect[:,2])
print(stat_dist)

[0.25 0.5  0.25]


We find that the limiting distribution coincides with the stationary distribution! This is a numerical verification of the theorem of the convergence of Markov chain, saying that if $\left\{X_n\right\}$ is an irreducible recurrent aperiodic Markov chain, then it has a unique stationary distribution $\pi$ and $X_n\overset{d}{\to}\pi\ (n\to\infty)$ (which we will learn in the following week, skip it if you don't understand for now).

Notice that the irreducibility, recurrence and aperiodicity conditions cannot be reduced. To see this, let's calculate the limiting distribution and stationary distribution for a different Markov chain as a counterexample.

In [36]:
# Now we have a two-state Markov chain with the following transition matrix
P = np.array([[0.0,1.0],[1.0,0.0]])
print(P)

[[0. 1.]
 [1. 0.]]


In [40]:
# Get the limit of such P, be careful that the limit actually does not exist here!
P_lim_1 = np.linalg.matrix_power(P,200)
P_lim_2 = np.linalg.matrix_power(P,201)
print(P_lim_1)
print(P_lim_2)

[[1. 0.]
 [0. 1.]]
[[0. 1.]
 [1. 0.]]


$P^n$ always alternates between those two matrices, so there's no limit for $P^n$! As a result, the limiting distribution does not exist for general initial distribution. However, the stationary distribution exists.

In [42]:
# Get eigen-decomposition of P^T
[eigenval,eigenvect] = linalg.eig(np.transpose(P))
eigenval

array([ 1., -1.])

In [43]:
# Take the eigenvector corresponding to eigenvalue 1 and normalize it such that all its components sum up to 1
stat_dist = eigenvect[:,0] / np.sum(eigenvect[:,0])
print(stat_dist)

[0.5 0.5]


This is a famous counterexample where the stationary distribution exists but the limiting distribution does not exist. The reason of the failure of the convergence theorem is that this Markov chain violates the aperiodic condition, in that it has period $2$ (alternates between different states). That's why we have to dintinguish limiting distribution and stationary distribution as two different concepts with connections.